spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/task-manager
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver